apiVersion: apps/v1
kind: Deployment
metadata:
  name: octant-deployment
  labels:
    app: octant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octant
  template:
    metadata:
      labels:
        app: octant
    spec:
      containers:
      - name: octant
        image: akibahiroki/octant:0.25.1
        ports:
        - containerPort: 8080
      serviceAccount: octant